"""added username and relationships between blogs, comments and users

Revision ID: 9fdacc459b7e
Revises: 6f907bef9f50
Create Date: 2019-11-28 12:59:26.065783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fdacc459b7e'
down_revision = '6f907bef9f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogpost', sa.Column('blog_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogpost', 'blog_title')
    # ### end Alembic commands ###
